name: Publish

on:
  push:
    branches: [ master ]

jobs:
  publish:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: src

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Publish
      run: dotnet publish --configuration Release --self-contained true --runtime win10-x64 --verbosity normal
